# Generated by Django 6.0.5 on 2026-06-11 04:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple", "Simple"),
                            ("analysis", "Analysis"),
                            ("deep_research", "Deep Research"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("route_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chain_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_run",
                        to="llm_analysis.chainrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
