# Generated by Django 6.0.5 on 2026-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0002_routerun"),
    ]

    operations = [
        migrations.AddField(
            model_name="routerun",
            name="route_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routerun",
            name="route_method",
            field=models.CharField(
                blank=True,
                choices=[("llm", "LLM classifier"), ("semantic", "Semantic embedding")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="routerun",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simple", "Simple"),
                    ("analysis", "Analysis"),
                    ("comparison", "Comparison"),
                    ("deep_research", "Deep Research"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
