# Generated by Django 6.0.5 on 2026-06-11 13:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0006_evaloptrun_evaloptiteration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanExecRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                ("max_steps", models.PositiveSmallIntegerField(default=6)),
                ("allow_replan", models.BooleanField(default=True)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("replans", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PlanExecStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("task", models.TextField(blank=True)),
                ("tool", models.CharField(blank=True, max_length=50)),
                ("tool_args", models.JSONField(blank=True, null=True)),
                ("observation", models.TextField(blank=True)),
                ("result", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="llm_analysis.planexecrun",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("run", "order")},
            },
        ),
    ]
