# Generated by Django 6.0.5 on 2026-06-11 14:55

from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0007_planexecrun_planexecstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        default=apps.llm_analysis.models._default_base_url, max_length=255
                    ),
                ),
                (
                    "main_model",
                    models.CharField(
                        default=apps.llm_analysis.models._default_main_model, max_length=100
                    ),
                ),
                (
                    "classifier_model",
                    models.CharField(
                        default=apps.llm_analysis.models._default_classifier_model, max_length=100
                    ),
                ),
                (
                    "embed_model",
                    models.CharField(
                        default=apps.llm_analysis.models._default_embed_model, max_length=100
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(default=apps.llm_analysis.models._default_timeout),
                ),
                (
                    "num_parallel",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_num_parallel
                    ),
                ),
                (
                    "route_mode",
                    models.CharField(
                        choices=[("llm", "Llm"), ("semantic", "Semantic")],
                        default=apps.llm_analysis.models._default_route_mode,
                        max_length=10,
                    ),
                ),
                (
                    "route_threshold",
                    models.FloatField(default=apps.llm_analysis.models._default_route_threshold),
                ),
                (
                    "react_max_steps",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_react_max_steps
                    ),
                ),
                (
                    "eval_max_iterations",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_eval_max_iterations
                    ),
                ),
                (
                    "eval_threshold",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_eval_threshold
                    ),
                ),
                (
                    "plan_max_steps",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_plan_max_steps
                    ),
                ),
                (
                    "plan_max_replans",
                    models.PositiveIntegerField(
                        default=apps.llm_analysis.models._default_plan_max_replans
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM settings",
            },
        ),
    ]
