# Generated by Django 6.0.5 on 2026-06-12 06:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0009_llmsettings_orch_max_workers_orchestratorrun_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="multiagent_max_tools",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_multiagent_max_tools
            ),
        ),
        migrations.CreateModel(
            name="MultiAgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                ("max_tools", models.PositiveSmallIntegerField(default=4)),
                ("agents", models.JSONField(blank=True, null=True)),
                ("route_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiagent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MultiAgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agent_id", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=50)),
                ("order", models.PositiveSmallIntegerField()),
                ("input", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="llm_analysis.multiagentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("run", "order")},
            },
        ),
    ]
