# Generated by Django 6.0.5 on 2026-06-12 10:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0011_llmsettings_dag_max_nodes_dagrun_dagnode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="auto_max_cycles",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_auto_max_cycles
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="auto_max_subagents",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_auto_max_subagents
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="auto_no_progress",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_auto_no_progress
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="auto_subagent_steps",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_auto_subagent_steps
            ),
        ),
        migrations.CreateModel(
            name="AutonomousRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                ("max_cycles", models.PositiveSmallIntegerField(default=8)),
                ("max_subagents", models.PositiveSmallIntegerField(default=3)),
                ("goal", models.TextField(blank=True)),
                ("backlog", models.JSONField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomous_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AutonomousCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("reflection", models.TextField(blank=True)),
                ("task", models.TextField(blank=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("tool", "Tool"), ("subagent", "Subagent"), ("reason", "Reason")],
                        default="reason",
                        max_length=10,
                    ),
                ),
                ("tool", models.CharField(blank=True, max_length=50)),
                ("tool_args", models.JSONField(blank=True, null=True)),
                ("observation", models.TextField(blank=True)),
                ("spawned", models.BooleanField(default=False)),
                ("subagent_steps", models.JSONField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("backlog", models.JSONField(blank=True, null=True)),
                ("goal_complete", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="llm_analysis.autonomousrun",
                    ),
                ),
            ],
            options={
                "ordering": ("index",),
                "unique_together": {("run", "index")},
            },
        ),
    ]
