# Generated by Django 6.0.5 on 2026-06-13 05:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0012_llmsettings_auto_max_cycles_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chain", "Prompt Chain"),
                            ("route", "Routing"),
                            ("parallel", "Parallelization"),
                            ("react", "ReAct"),
                            ("eval_opt", "Evaluator-Optimizer"),
                            ("plan_exec", "Plan-and-Execute"),
                            ("orchestrator", "Orchestrator-Workers"),
                            ("multiagent", "Multi-Agent (Sequential)"),
                            ("dag", "Multi-Agent (Parallel/DAG)"),
                            ("autonomous", "Autonomous"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField()),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("done", "Done"), ("error", "Error")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("max_steps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_iterations", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("threshold", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_workers", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_tools", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_nodes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_cycles", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_subagents", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("allow_replan", models.BooleanField(blank=True, null=True)),
                ("strategy", models.CharField(blank=True, max_length=12)),
                ("n", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("tally", models.JSONField(blank=True, null=True)),
                ("best_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("replans", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("agents", models.JSONField(blank=True, null=True)),
                ("route", models.CharField(blank=True, max_length=20)),
                ("route_reason", models.TextField(blank=True)),
                ("route_method", models.CharField(blank=True, max_length=10)),
                ("route_confidence", models.FloatField(blank=True, null=True)),
                ("goal", models.TextField(blank=True)),
                ("backlog", models.JSONField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=20)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="llm_analysis.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(blank=True, max_length=50)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("thought", models.TextField(blank=True)),
                ("tool", models.CharField(blank=True, max_length=50)),
                ("tool_args", models.JSONField(blank=True, null=True)),
                ("observation", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                ("result", models.TextField(blank=True)),
                ("is_answer", models.BooleanField(default=False)),
                ("draft", models.TextField(blank=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("passed", models.BooleanField(default=False)),
                ("vote", models.CharField(blank=True, max_length=20)),
                ("task", models.TextField(blank=True)),
                ("input", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(blank=True, null=True)),
                ("depends_on", models.JSONField(blank=True, default=list)),
                ("wave", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=10)),
                ("spawned", models.BooleanField(default=False)),
                ("subagent_steps", models.JSONField(blank=True, null=True)),
                ("reflection", models.TextField(blank=True)),
                ("backlog", models.JSONField(blank=True, null=True)),
                ("goal_complete", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="llm_analysis.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("run", "order")},
            },
        ),
    ]
