"""Drop all 19 legacy per-workflow tables now that every workflow reads/writes the
unified AgentRun/AgentStep models (llm_analysis model consolidation, GOAL phase).

Hand-written as ordered ``DeleteModel`` operations (child tables and the route table -
which FKs ChainRun - before the parent run tables) so the drop is FK-safe and avoids the
SQLite table-remake the autogenerated ``RemoveField`` operations would trigger.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0023_migrate_route_to_agentrun"),
    ]

    operations = [
        # --- child tables first ---
        migrations.DeleteModel(name="ChainStepResult"),
        migrations.DeleteModel(name="ReactStep"),
        migrations.DeleteModel(name="EvalOptIteration"),
        migrations.DeleteModel(name="PlanExecStep"),
        migrations.DeleteModel(name="OrchestratorWorker"),
        migrations.DeleteModel(name="MultiAgentStep"),
        migrations.DeleteModel(name="DagNode"),
        migrations.DeleteModel(name="AutonomousCycle"),
        migrations.DeleteModel(name="ParallelTaskResult"),
        # --- route references ChainRun, so drop it before ChainRun ---
        migrations.DeleteModel(name="RouteRun"),
        # --- parent run tables ---
        migrations.DeleteModel(name="ChainRun"),
        migrations.DeleteModel(name="ReactRun"),
        migrations.DeleteModel(name="EvalOptRun"),
        migrations.DeleteModel(name="PlanExecRun"),
        migrations.DeleteModel(name="OrchestratorRun"),
        migrations.DeleteModel(name="MultiAgentRun"),
        migrations.DeleteModel(name="DagRun"),
        migrations.DeleteModel(name="AutonomousRun"),
        migrations.DeleteModel(name="ParallelRun"),
    ]
