# Generated by Django 6.0.5 on 2026-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0024_remove_autonomousrun_user_remove_chainrun_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentstep",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
