# Generated by Django 6.0.5 on 2026-08-05 10:31

from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0035_remove_agentrun_agents_remove_agentrun_allow_replan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="browser_allowed_domains",
            field=models.TextField(
                blank=True, default=apps.llm_analysis.models._default_browser_allowed_domains
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_enabled",
            field=models.BooleanField(default=apps.llm_analysis.models._default_browser_enabled),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_headless",
            field=models.BooleanField(default=apps.llm_analysis.models._default_browser_headless),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_max_steps",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_browser_max_steps
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_model",
            field=models.CharField(
                default=apps.llm_analysis.models._default_browser_model, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_provider",
            field=models.CharField(
                choices=[("anthropic", "Anthropic"), ("ollama", "Ollama")],
                default=apps.llm_analysis.models._default_browser_provider,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="browser_timeout_s",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_browser_timeout
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chain", "Prompt Chain"),
                    ("route", "Routing"),
                    ("parallel", "Parallelization"),
                    ("react", "ReAct"),
                    ("eval_opt", "Evaluator-Optimizer"),
                    ("plan_exec", "Plan-and-Execute"),
                    ("orchestrator", "Orchestrator-Workers"),
                    ("multiagent", "Multi-Agent (Sequential)"),
                    ("dag", "Multi-Agent (Parallel/DAG)"),
                    ("autonomous", "Autonomous"),
                    ("browser", "Browser (web)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
