# Generated by Django 6.0.5 on 2026-09-16 08:57

from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0036_llmsettings_browser_allowed_domains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="summary_financials_max_age_days",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_summary_financials_max_age
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="summary_price_max_age_days",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_summary_price_max_age
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="summary_snapshot_max_age_days",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_summary_snapshot_max_age
            ),
        ),
    ]
