# Generated by Django 6.0.5 on 2026-09-25 09:05

from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0037_llmsettings_summary_financials_max_age_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="num_ctx",
            field=models.PositiveIntegerField(default=apps.llm_analysis.models._default_num_ctx),
        ),
    ]
