# Generated by Django 6.0.5 on 2026-09-28 06:07

from django.db import migrations, models

import apps.llm_analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_analysis", "0038_add_llmsettings_num_ctx"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="chat_max_steps",
            field=models.PositiveIntegerField(
                default=apps.llm_analysis.models._default_chat_max_steps
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chain", "Prompt Chain"),
                    ("route", "Routing"),
                    ("parallel", "Parallelization"),
                    ("react", "ReAct"),
                    ("eval_opt", "Evaluator-Optimizer"),
                    ("plan_exec", "Plan-and-Execute"),
                    ("orchestrator", "Orchestrator-Workers"),
                    ("multiagent", "Multi-Agent (Sequential)"),
                    ("dag", "Multi-Agent (Parallel/DAG)"),
                    ("autonomous", "Autonomous"),
                    ("browser", "Browser (web)"),
                    ("chat", "Chat"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
