export const queryKeys = {
  auth: {
    me: () => ["auth", "me"] as const,
  },
  companies: {
    all: () => ["companies"] as const,
    list: (params?: object) => ["companies", "list", params] as const,
    detail: (id: number | string) => ["companies", "detail", id] as const,
    sectors: () => ["companies", "sectors"] as const,
    industries: (params?: object) => ["companies", "industries", params] as const,
    marketHierarchy: (metric: import("@/types/companies").MarketHierarchyMetric = "count") =>
      ["companies", "market-hierarchy", metric] as const,
    prices: (companyId: number) => ["companies", companyId, "prices"] as const,
    snapshots: (companyId: number) => ["companies", companyId, "snapshots"] as const,
    financials: (companyId: number) => ["companies", companyId, "financials"] as const,
    financialsPivoted: (companyId: number) => ["companies", companyId, "financials-pivoted"] as const,
    dividends: (companyId: number) => ["companies", companyId, "dividends"] as const,
    shortInterest: (companyId: number) => ["companies", companyId, "short-interest"] as const,
    institutionalHolders: (companyId: number) => ["companies", companyId, "institutional-holders"] as const,
    earningsDates: (companyId: number, params?: object) => ["companies", companyId, "earnings-dates", params] as const,
    optionsExpiries: (companyId: number) => ["companies", companyId, "options"] as const,
    optionsChain: (companyId: number, expiryDate: string) => ["companies", companyId, "options", expiryDate] as const,
    syncStatus: (companyId: number) => ["companies", companyId, "sync-status"] as const,
    syncFreshness: () => ["companies", "sync-freshness"] as const,
    syncFreshnessMatrix: () => ["companies", "sync-freshness", "matrix"] as const,
    summaryFreshness: () => ["companies", "summary-freshness"] as const,
    summaryLatest: (symbol: string) => ["companies", symbol, "summary-latest"] as const,
    summaryList: (symbol: string) => ["companies", symbol, "summaries"] as const,
  },
  system: {
    health: () => ["system", "health"] as const,
  },
  tasks: {
    results: (status?: string) => ["tasks", "results", status] as const,
    result: (id: string) => ["tasks", "result", id] as const,
    schedules: () => ["tasks", "schedules"] as const,
  },
  redis: {
    info: () => ["redis", "info"] as const,
    keys: (prefix?: string) => ["redis", "keys", prefix] as const,
    keyValue: (key: string) => ["redis", "key", key] as const,
  },
  // Browser agent lives on its own page (/browse) and keeps its own key namespace -
  // deliberately not folded into llm.allRuns(), which backs the Agents history.
  chat: {
    sessions: () => ["chat", "sessions"] as const,
    session: (id: string) => ["chat", "session", id] as const,
  },
  browser: {
    runs: () => ["browser", "runs"] as const,
    runDetail: (id: string) => ["browser", "run", id] as const,
    screenshot: (runId: string, order: number) =>
      ["browser", "screenshot", runId, order] as const,
  },
  llm: {
    models: () => ["llm", "models"] as const,
    settings: () => ["llm", "settings"] as const,
    allRuns: () => ["llm", "all-runs"] as const,
    chainRuns: () => ["llm", "chain-runs"] as const,
    chainRunDetail: (id: string) => ["llm", "chain-run", id] as const,
    routeRuns: () => ["llm", "route-runs"] as const,
    routeRunDetail: (id: string) => ["llm", "route-run", id] as const,
    parallelRuns: () => ["llm", "parallel-runs"] as const,
    parallelRunDetail: (id: string) => ["llm", "parallel-run", id] as const,
    reactRuns: () => ["llm", "react-runs"] as const,
    reactRunDetail: (id: string) => ["llm", "react-run", id] as const,
    evalOptRuns: () => ["llm", "eval-opt-runs"] as const,
    evalOptRunDetail: (id: string) => ["llm", "eval-opt-run", id] as const,
    planRuns: () => ["llm", "plan-runs"] as const,
    planRunDetail: (id: string) => ["llm", "plan-run", id] as const,
    orchestratorRuns: () => ["llm", "orchestrator-runs"] as const,
    orchestratorRunDetail: (id: string) => ["llm", "orchestrator-run", id] as const,
    multiAgentRuns: () => ["llm", "multiagent-runs"] as const,
    multiAgentRunDetail: (id: string) => ["llm", "multiagent-run", id] as const,
    dagRuns: () => ["llm", "dag-runs"] as const,
    dagRunDetail: (id: string) => ["llm", "dag-run", id] as const,
    autonomousRuns: () => ["llm", "autonomous-runs"] as const,
    autonomousRunDetail: (id: string) => ["llm", "autonomous-run", id] as const,
  },
  knowledge: {
    concepts: (params?: object) => ["knowledge", "concepts", params] as const,
    concept: (id: string) => ["knowledge", "concept", id] as const,
    graph: (id: string, hops: number) => ["knowledge", "graph", id, hops] as const,
  },
  codegraph: {
    graph: (params?: object) => ["codegraph", "graph", params] as const,
    node: (id: string) => ["codegraph", "node", id] as const,
  },
};
