# Generated by Django 6.0.5 on 2026-05-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "exchange",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NYSE", "New York Stock Exchange"),
                            ("NASDAQ", "NASDAQ"),
                            ("AMEX", "American Stock Exchange"),
                            ("NYSE_ARCA", "NYSE Arca"),
                            ("LSE", "London Stock Exchange"),
                            ("ASX", "Australian Securities Exchange"),
                            ("TSX", "Toronto Stock Exchange"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("CHF", "Swiss Franc"),
                            ("HKD", "Hong Kong Dollar"),
                            ("CNY", "Chinese Yuan"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.industry",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="companies.sector",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["symbol"],
            },
        ),
        migrations.AddField(
            model_name="industry",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="industries",
                to="companies.sector",
            ),
        ),
        migrations.CreateModel(
            name="CompanySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("market_cap", models.BigIntegerField(null=True)),
                ("trailing_pe", models.FloatField(null=True)),
                ("forward_pe", models.FloatField(null=True)),
                ("price_to_book", models.FloatField(null=True)),
                ("debt_to_equity", models.FloatField(null=True)),
                ("return_on_equity", models.FloatField(null=True)),
                ("profit_margins", models.FloatField(null=True)),
                ("dividend_yield", models.FloatField(null=True)),
                ("trailing_eps", models.FloatField(null=True)),
                ("forward_eps", models.FloatField(null=True)),
                ("raw", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "fetched_at"], name="companies_c_company_399506_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "date")},
            },
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("income", "Income Statement"),
                            ("balance", "Balance Sheet"),
                            ("cashflow", "Cash Flow"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("annual", "Annual"), ("quarterly", "Quarterly")], max_length=10
                    ),
                ),
                ("period_end", models.DateField()),
                ("metric", models.CharField(max_length=100)),
                ("value", models.FloatField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "statement_type", "period_end"],
                        name="companies_f_company_b19747_idx",
                    )
                ],
                "unique_together": {
                    ("company", "statement_type", "period", "period_end", "metric")
                },
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=4, max_digits=14)),
                ("high", models.DecimalField(decimal_places=4, max_digits=14)),
                ("low", models.DecimalField(decimal_places=4, max_digits=14)),
                ("close", models.DecimalField(decimal_places=4, max_digits=14)),
                ("volume", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "date"], name="companies_p_company_67c9e8_idx")
                ],
                "unique_together": {("company", "date")},
            },
        ),
    ]
