# Generated by Django 6.0.5 on 2026-05-28 14:07

from django.db import migrations, models


def mark_existing_bootstrapped(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Company.objects.all().update(is_bootstrapped=True)


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("companies", "0002_add_timestamps"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="company",
            name="is_bootstrapped",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(mark_existing_bootstrapped, migrations.RunPython.noop),
    ]
