# Generated by Django 6.0.5 on 2026-06-02 03:00

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0003_add_is_bootstrapped"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="full_time_employees",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="ir_website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="officers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="audit_risk",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="average_volume",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="beta",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="board_risk",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="book_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="compensation_risk",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="current_ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="dividend_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="earnings_growth",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="earnings_quarterly_growth",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="ebitda",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="ebitda_margins",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="enterprise_to_ebitda",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="enterprise_to_revenue",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="enterprise_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="ex_dividend_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="fifty_day_average",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="fifty_two_week_high",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="fifty_two_week_low",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="five_year_avg_dividend_yield",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="float_shares",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="free_cashflow",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="gross_margins",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="held_pct_insiders",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="held_pct_institutions",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="last_dividend_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="last_dividend_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="last_fiscal_year_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="last_split_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="last_split_factor",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="most_recent_quarter",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="net_income_to_common",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="next_fiscal_year_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="num_analyst_opinions",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="operating_cashflow",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="operating_margins",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="overall_risk",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="payout_ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="peg_ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="price_to_sales",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="quick_ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="recommendation_key",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="recommendation_mean",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="recommendations_breakdown",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="return_on_assets",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="revenue_growth",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="revenue_per_share",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="sandp52_week_change",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="shareholder_rights_risk",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="shares_outstanding",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="target_high_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="target_low_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="target_mean_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="target_median_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="total_cash",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="total_cash_per_share",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="trailing_annual_dividend_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="trailing_peg_ratio",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="two_hundred_day_average",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysnapshot",
            name="week52_change",
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name="OptionsExpiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("fetched_at", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_expiries",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
                "unique_together": {("company", "expiry_date", "fetched_at")},
            },
        ),
        migrations.CreateModel(
            name="EarningsDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("earnings_date", models.DateField()),
                ("eps_estimate", models.FloatField(null=True)),
                ("reported_eps", models.FloatField(null=True)),
                ("surprise_pct", models.FloatField(null=True)),
                ("is_upcoming", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings_dates",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-earnings_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "is_upcoming"], name="companies_e_company_c6de90_idx"
                    )
                ],
                "unique_together": {("company", "earnings_date")},
            },
        ),
        migrations.CreateModel(
            name="ESGScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("total_esg", models.FloatField(null=True)),
                ("environment_score", models.FloatField(null=True)),
                ("social_score", models.FloatField(null=True)),
                ("governance_score", models.FloatField(null=True)),
                ("esg_performance", models.CharField(max_length=20, null=True)),
                ("raw", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esg_scores",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "fetched_at"], name="companies_e_company_39b9ff_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalHolderSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("holders", models.JSONField(default=list)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutional_holder_snapshots",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "fetched_at"], name="companies_i_company_f958cd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionsContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "option_type",
                    models.CharField(choices=[("call", "Call"), ("put", "Put")], max_length=4),
                ),
                ("contract_symbol", models.CharField(max_length=30)),
                ("strike", models.DecimalField(decimal_places=2, max_digits=12)),
                ("last_price", models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ("bid", models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ("ask", models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ("volume", models.IntegerField(null=True)),
                ("open_interest", models.IntegerField(null=True)),
                ("implied_volatility", models.FloatField(null=True)),
                ("in_the_money", models.BooleanField(null=True)),
                (
                    "expiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="companies.optionsexpiry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expiry", "option_type", "strike"],
                        name="companies_o_expiry__d67053_idx",
                    )
                ],
                "unique_together": {("expiry", "option_type", "contract_symbol")},
            },
        ),
        migrations.CreateModel(
            name="ShortInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("date_short_interest", models.DateField(null=True)),
                ("shares_short", models.BigIntegerField(null=True)),
                ("shares_short_prior_month", models.BigIntegerField(null=True)),
                ("short_ratio", models.FloatField(null=True)),
                ("short_pct_of_float", models.FloatField(null=True)),
                ("shares_pct_shares_out", models.FloatField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_interest",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "fetched_at"], name="companies_s_company_f59d44_idx"
                    )
                ],
            },
        ),
    ]
