# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: list = [  # noqa: RUF012
        ("companies", "0004_company_address_company_city_company_country_and_more"),
    ]

    operations: list = [  # noqa: RUF012
        migrations.AddField(
            model_name="earningsdate",
            name="fetched_at",
            field=models.DateTimeField(null=True),
        ),
    ]
