# Generated by Django 6.0.5 on 2026-06-02 13:09

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0005_add_earningsdate_fetched_at"),
    ]

    operations: ClassVar = [
        migrations.RemoveIndex(
            model_name="esgscore",
            name="companies_e_company_39b9ff_idx",
        ),
        migrations.DeleteModel(
            name="ESGScore",
        ),
    ]
