# Generated by Django 6.0.5 on 2026-06-03 08:35

from __future__ import annotations

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0006_remove_esgscore_companies_e_company_39b9ff_idx_and_more"),
    ]

    operations: ClassVar = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("symbol",), "verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="companysnapshot",
            options={"ordering": ("-fetched_at",)},
        ),
        migrations.AlterModelOptions(
            name="earningsdate",
            options={"ordering": ("-earnings_date",)},
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={"ordering": ("name",), "verbose_name_plural": "industries"},
        ),
        migrations.AlterModelOptions(
            name="institutionalholdersnapshot",
            options={"ordering": ("-fetched_at",)},
        ),
        migrations.AlterModelOptions(
            name="optionsexpiry",
            options={"ordering": ("expiry_date",)},
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="shortinterest",
            options={"ordering": ("-fetched_at",)},
        ),
    ]
