# Generated by Django 6.0.5 on 2026-06-03 12:30

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0007_alter_company_options_alter_companysnapshot_options_and_more"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="CompanySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("hold", "Hold"),
                            ("sell", "Sell"),
                            ("insufficient_data", "Insufficient Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("data_snapshot", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-generated_at",),
                "indexes": [
                    models.Index(
                        fields=["company", "generated_at"], name="companies_c_company_c1c2b8_idx"
                    )
                ],
            },
        ),
    ]
