# Generated by Django 6.0.5 on 2026-06-03 13:41

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0008_companysummary"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="CompanySyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("price", "Price"),
                            ("snapshot", "Snapshot"),
                            ("profile", "Profile"),
                            ("financials", "Financials"),
                            ("dividends", "Dividends"),
                            ("earnings_dates", "Earnings Dates"),
                            ("institutional_holders", "Institutional Holders"),
                            ("options", "Options"),
                        ],
                        max_length=30,
                    ),
                ),
                ("last_synced_at", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sync_type", "last_synced_at"],
                        name="companies_c_sync_ty_81390d_idx",
                    )
                ],
                "unique_together": {("company", "sync_type")},
            },
        ),
    ]
