# Generated by Django 6.0.5 on 2026-06-03 14:43

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("companies", "0009_companysyncrecord"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="companysyncrecord",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("price", "Price"),
                    ("snapshot", "Snapshot"),
                    ("profile", "Profile"),
                    ("financials", "Financials"),
                    ("dividends", "Dividends"),
                    ("earnings_dates", "Earnings Dates"),
                    ("institutional_holders", "Institutional Holders"),
                    ("options", "Options"),
                    ("short_interest", "Short Interest"),
                ],
                max_length=30,
            ),
        ),
    ]
