# Generated by Django 6.0.5 on 2026-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0012_backfill_percent_to_fraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysummary",
            name="confidence",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="companysummary",
            name="key_drivers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="companysummary",
            name="key_risks",
            field=models.JSONField(default=list),
        ),
    ]
