/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedisRouteImport } from './routes/redis'
import { Route as MarketMapRouteImport } from './routes/market-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CodeGraphRouteImport } from './routes/code-graph'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisRoute = RedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMapRoute = MarketMapRouteImport.update({
  id: '/market-map',
  path: '/market-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeGraphRoute = CodeGraphRouteImport.update({
  id: '/code-graph',
  path: '/code-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/code-graph': typeof CodeGraphRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/market-map': typeof MarketMapRoute
  '/redis': typeof RedisRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/code-graph': typeof CodeGraphRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/market-map': typeof MarketMapRoute
  '/redis': typeof RedisRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/code-graph': typeof CodeGraphRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/market-map': typeof MarketMapRoute
  '/redis': typeof RedisRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/browse'
    | '/chat'
    | '/code-graph'
    | '/companies'
    | '/knowledge'
    | '/login'
    | '/market-map'
    | '/redis'
    | '/register'
    | '/tasks'
    | '/companies/$id'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/browse'
    | '/chat'
    | '/code-graph'
    | '/knowledge'
    | '/login'
    | '/market-map'
    | '/redis'
    | '/register'
    | '/tasks'
    | '/companies/$id'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/browse'
    | '/chat'
    | '/code-graph'
    | '/companies'
    | '/knowledge'
    | '/login'
    | '/market-map'
    | '/redis'
    | '/register'
    | '/tasks'
    | '/companies/$id'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BrowseRoute: typeof BrowseRoute
  ChatRoute: typeof ChatRoute
  CodeGraphRoute: typeof CodeGraphRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MarketMapRoute: typeof MarketMapRoute
  RedisRoute: typeof RedisRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis': {
      id: '/redis'
      path: '/redis'
      fullPath: '/redis'
      preLoaderRoute: typeof RedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-map': {
      id: '/market-map'
      path: '/market-map'
      fullPath: '/market-map'
      preLoaderRoute: typeof MarketMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-graph': {
      id: '/code-graph'
      path: '/code-graph'
      fullPath: '/code-graph'
      preLoaderRoute: typeof CodeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BrowseRoute: BrowseRoute,
  ChatRoute: ChatRoute,
  CodeGraphRoute: CodeGraphRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MarketMapRoute: MarketMapRoute,
  RedisRoute: RedisRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
