# Generated by Django 6.0.5 on 2026-06-24 11:43

from django.db import migrations, models


def backfill_base_slug(apps, schema_editor):
    # Existing rows are all the default sense, so their base (lexical) key is just their slug.
    Concept = apps.get_model("knowledge_graph", "Concept")
    Concept.objects.update(base_slug=models.F("slug"))


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0004_prerequisite_of_to_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="base_slug",
            field=models.SlugField(blank=True, default="", max_length=200),
        ),
        migrations.RunPython(backfill_base_slug, migrations.RunPython.noop),
    ]
