# Generated by Django 6.0.5 on 2026-06-30 07:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0005_concept_base_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="knowledge_graph.concept",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "concept aliases",
                "ordering": ("name",),
            },
        ),
    ]
