# Generated by Django 6.0.5 on 2026-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0006_conceptalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="negative_description",
            field=models.TextField(blank=True),
        ),
    ]
